import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Lato } from "@next/font/google";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const themes = {
  dark: {
    background: "black",
    color: "white",
  },
  light: {
    background: "white",
    color: "black",
  },
};

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// function Navbar({ pageId }) {
//   return (
//     <div className="flex justify-center max-w-7xl mx-auto h-16 pt-6">
//       <nav>
//         <ul
//           className="flex rounded-full bg-white/90 px-4 text-sm fontmedium text-zinc-800 shadow-lg shadow-zinc-800/5 ring-1 ring-zinc-900/5
// backdrop-blur"
//         >
//           <NavItem
//             title={"About Me"}
//             url={"/"}
//             isSelected={pageId == "about me"}
//           />
//           <NavItem
//             title={"Projects"}
//             url={"/projects"}
//             isSelected={pageId == "projects"}
//           />
//           <NavItem
//             title={"Essays"}
//             url={"/essays"}
//             isSelected={pageId == "essays"}
//           />
//         </ul>
//       </nav>
//     </div>
//   );
// }

// function NavItem({ title, url, isSelected }) {
//   return (
//     <li>
//       <a
//         href={url}
//         className={`block px-3 py-2 transition hover:text-teal-500 ${
//           isSelected ? "text-teal-500" : ""
//         }`}
//       >
//         {title}
//       </a>
//     </li>
//   );
// }

function FooterLinks({ text, url }) {
  return (
    <a className="transition hover:text-teal-500" href={url}>
      {text}
    </a>
  );
}

function Footer() {
  return (
    <footer className="pt-10 px-8 pb-16 border-t">
      <div className="flex justify-between gap-6">
        <div className="flex gap-6 text-sm font-medium text-zinc-600">
          <FooterLinks text={"About Me"} url={"/"} />
          <FooterLinks text={"Projects"} url={"/projects"} />
          <FooterLinks text={"Essays"} url={"/essays"} />
        </div>
        <p className="text-sm text-zinc-400">
          2023 EmyraldCorp. All rights reserverd
        </p>
      </div>
    </footer>
  );
}
export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={lato.className}>
          <Navbar />

          {children}
        </body>
      </html>
    </>
  );
}
